#
# This Makefile was generated by Code::Blocks IDE.
#

SRCS_f90d1 = \
xmlparse.f90 \
main.f90 \
xmlwrite.f90 

SRCS_f95d1 = \
global.f95 \
input.f95 \
general.f95 \
constants.f95 \
declrs.f95 

OBJS_f90d1 = \
xmlparse.o \
main.o \
xmlwrite.o 

OBJS_f95d1 = \
global.o \
input.o \
general.o \
constants.o \
declrs.o 

SRC_DIR_f90d1 = 

SRC_DIR_f95d1 = 
OBJS_DIR = obj/Release/
EXE_DIR = bin/Release/

EXE = mcnp_to_openmc
FC = gfortran
LD = gfortran
IDIR = 
CFLAGS = -Wall -O2 -w -fcheck=bounds -fcheck=all  -J$(OBJS_DIR) $(IDIR)
LFLAGS = -s 
LIBS = 

VPATH = $(SRC_DIR_f90d1):$(OBJS_DIR):$(SRC_DIR_f95d1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_f90d1) $(OBJS_f95d1))

all : $(EXE)

$(EXE) : $(OBJS_f90d1) $(OBJS_f95d1)
	@mkdir -p $(EXE_DIR)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)
	rm -r *obj
	./bin/Release/mcnp_to_openmc

$(OBJS_f90d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d1)$(@:.o=.f90) -o $(OBJS_DIR)$@

$(OBJS_f95d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f95d1)$(@:.o=.f95) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# Dependencies of files
xmlparse.o: \
    xmlparse.f90
main.o: \
    main.f90 \
    input.o \
    xmlwrite.o
xmlwrite.o: \
    xmlwrite.f90 \
    global.o \
    input.o \
    xmlparse.o
global.o: \
    global.f95 \
    declrs.o
input.o: \
    input.f95 \
    constants.o \
    general.o \
    global.o
general.o: \
    general.f95 \
    constants.o
constants.o: \
    constants.f95
declrs.o: \
    declrs.f95 \
    constants.o \
    general.o

